# Generated by Django 3.1.1 on 2020-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0010_auto_20201004_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
