# Generated by Django 3.1.1 on 2020-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.SteamGame'),
        ),
    ]
