# Generated by Django 3.1.1 on 2020-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
