# Generated by Django 3.1.1 on 2020-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_uuid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('event', 'game', 'username'), name='unique vote'),
        ),
    ]
