# Generated by Django 3.1.1 on 2020-10-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201001_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SteamGame',
            new_name='Game',
        ),
    ]
