# Generated by Django 3.1.1 on 2021-01-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allow_leaving_event_details_blank_in_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
