# Generated by Django 3.1.1 on 2020-10-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='store_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
