# Generated by Django 3.1.13 on 2022-07-03 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_eventsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
