# Generated by Django 3.1.1 on 2020-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201004_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='store_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
