# Generated by Django 3.1.13 on 2022-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_eventsubscription_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentMail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sender", models.CharField(max_length=256)),
                ("recipient", models.CharField(max_length=256)),
                ("subject", models.TextField()),
                ("body", models.TextField()),
                ("html", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
