# Generated by Django 3.2.14 on 2022-10-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20221024_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="softdeleted",
            field=models.BooleanField(default=False),
        ),
    ]
